### ISSUE TITLE
Invidual wallet can verify activity on network 

### ISSUE THREAD

**Issue by Avnsmith** [zkcrossteam/zkWasm-service-helper#9]
I just connect my wallet to https://explorer.zkwasmhub.com/
I my wallet can verify a action on network (manual verify ) 

https://github.com/zkcrossteam/zkWasm-service-helper/assets/118146778/f132757c-297a-417b-b00e-18787453c51e

I think this job become to Node, right?

**Comment by geofarmbuilder** [comment]
This is the service helper in golang, has nothing to with becoming node or not.
